/* Resource Datei Indizes fÅr SPHERICA */

#define SPH_MAIN         0   /* Formular/Dialog */
#define _TIT             2   /* TEXT in Baum SPH_MAIN */
#define KR_F             3   /* BOX in Baum SPH_MAIN */
#define KR_R             4   /* BOX in Baum SPH_MAIN */
#define KR_A             5   /* BOXTEXT in Baum SPH_MAIN */
#define KG_F             7   /* BOX in Baum SPH_MAIN */
#define KG_R             8   /* BOX in Baum SPH_MAIN */
#define KG_A             9   /* BOXTEXT in Baum SPH_MAIN */
#define KB_F             11  /* BOX in Baum SPH_MAIN */
#define KB_R             12  /* BOX in Baum SPH_MAIN */
#define KB_A             13  /* BOXTEXT in Baum SPH_MAIN */
#define TEXTURE_BOX      14  /* BOX in Baum SPH_MAIN */
#define TEXT_A           16  /* BOXTEXT in Baum SPH_MAIN */
#define TEXT_F           17  /* BOX in Baum SPH_MAIN */
#define TEXT_R           18  /* BOX in Baum SPH_MAIN */
#define TEX_XSC          23  /* FTEXT in Baum SPH_MAIN */
#define TEX_YSC          24  /* FTEXT in Baum SPH_MAIN */
#define TEX_XOFF         25  /* FTEXT in Baum SPH_MAIN */
#define TEX_YOFF         26  /* FTEXT in Baum SPH_MAIN */
#define ROUGH_BOX        29  /* BOX in Baum SPH_MAIN */
#define ROUGH_A          31  /* BOXTEXT in Baum SPH_MAIN */
#define ROUGH_F          32  /* BOX in Baum SPH_MAIN */
#define ROUGH_R          33  /* BOX in Baum SPH_MAIN */
#define TRANSP_BOX       34  /* BOX in Baum SPH_MAIN */
#define TRANSP_A         36  /* BOXTEXT in Baum SPH_MAIN */
#define TRANSP_F         37  /* BOX in Baum SPH_MAIN */
#define TRANSP_R         38  /* BOX in Baum SPH_MAIN */
#define TRAN_IDX         39  /* FTEXT in Baum SPH_MAIN */
#define BUMP_BOX         41  /* BOX in Baum SPH_MAIN */
#define BUMP_A           42  /* BOXTEXT in Baum SPH_MAIN */
#define BUMP_F           43  /* BOX in Baum SPH_MAIN */
#define BUMP_R           44  /* BOX in Baum SPH_MAIN */
#define BUMP_XSC         49  /* FTEXT in Baum SPH_MAIN */
#define BUMP_YSC         50  /* FTEXT in Baum SPH_MAIN */
#define BUMP_XOFF        51  /* FTEXT in Baum SPH_MAIN */
#define BUMP_YOFF        52  /* FTEXT in Baum SPH_MAIN */
#define BUMP_PERSP       56  /* IBOX in Baum SPH_MAIN */
#define XRAD             59  /* FTEXT in Baum SPH_MAIN */
#define LOS              63  /* BUTTON in Baum SPH_MAIN */
#define PREV_BOX         65  /* BOX in Baum SPH_MAIN */
#define BUMP_RADIO       70  /* IBOX in Baum SPH_MAIN */
#define TEXT_RADIO       74  /* IBOX in Baum SPH_MAIN */
#define ROUGH_RADIO      75  /* IBOX in Baum SPH_MAIN */
#define TRANSP_RADIO     76  /* IBOX in Baum SPH_MAIN */
#define BUMP_CHECK       77  /* IBOX in Baum SPH_MAIN */
#define TEXT_CHECK       78  /* IBOX in Baum SPH_MAIN */
#define ROUGH_CHECK      79  /* IBOX in Baum SPH_MAIN */
#define TRANS_CHECK      80  /* IBOX in Baum SPH_MAIN */
#define AR_F             84  /* BOX in Baum SPH_MAIN */
#define AR_R             85  /* BOX in Baum SPH_MAIN */
#define AR_A             86  /* BOXTEXT in Baum SPH_MAIN */
#define AG_F             88  /* BOX in Baum SPH_MAIN */
#define AG_R             89  /* BOX in Baum SPH_MAIN */
#define AG_A             90  /* BOXTEXT in Baum SPH_MAIN */
#define AB_F             92  /* BOX in Baum SPH_MAIN */
#define AB_R             93  /* BOX in Baum SPH_MAIN */
#define AB_A             94  /* BOXTEXT in Baum SPH_MAIN */
#define SSTR_F           97  /* BOX in Baum SPH_MAIN */
#define SSTR_R           98  /* BOX in Baum SPH_MAIN */
#define SSTR_A           99  /* BOXTEXT in Baum SPH_MAIN */
#define SPOW_F           101 /* BOX in Baum SPH_MAIN */
#define SPOW_R           102 /* BOX in Baum SPH_MAIN */
#define SPOW_A           103 /* BOXTEXT in Baum SPH_MAIN */
#define SFLT_F           105 /* BOX in Baum SPH_MAIN */
#define SFLT_R           106 /* BOX in Baum SPH_MAIN */
#define SFLT_A           107 /* BOXTEXT in Baum SPH_MAIN */
